version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: event_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=pwd # Redis 비밀번호 (원하면 제거 가능)
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "pwd"]

volumes:
  redis_data:
    driver: local
