version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      #- APP_ENV=production
      #- APP_DEBUG=false
      - APP_KEY=${APP_KEY}
    depends_on:
      - mysql
    command: php-fpm

  webserver:
    image: nginx:stable-alpine
    container_name: laravel_webserver
    restart: always
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["composer", "install"]

  artisan:
    image: php:8.1-fpm
    container_name: laravel_artisan
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

volumes:
  db_data:
